# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['flask_wrapper.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('instance', 'instance'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_cors',
        'flask_migrate',
        'sqlalchemy',
        'werkzeug',
        'jinja2',
        'click',
        'itsdangerous',
        'markupsafe',
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.platypus',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.pdfbase',
        'reportlab.pdfbase.ttfonts',
        'reportlab.lib.colors',
        'reportlab.lib.enums',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'PIL',
        'PIL.Image',
        'requests',
        'urllib3',
        'certifi',
        'chardet',
        'idna',
        'greenlet',
        'typing_extensions',
        'alembic',
        'mako',
        'pandas',
        'numpy',
        'openpyxl',
        'xlrd',
        'xlsxwriter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'scikit-learn',
        'notebook',
        'jupyter',
        'ipython',
        'pytest',
        'pylint',
        'black',
        'mypy',
        'flake8',
        'coverage',
        'sphinx',
        'tkinter',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Kutuphane_Yonetim_Sistemi',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)