#!/bin/bash
# Railway Domain Değiştirme Rehberi
# Bu script Railway Dashboard'dan domain değiştirme adımlarını gösterir

echo "🌐 Railway Domain Değiştirme Rehberi"
echo "======================================"
echo ""
echo "Railway CLI ile domain değiştirmek mümkün değil."
echo "Railway Dashboard'dan yapılması gerekiyor."
echo ""
echo "📋 ADIMLAR:"
echo ""
echo "1. Railway Dashboard'a gidin:"
echo "   https://railway.app"
echo ""
echo "2. Projeye gidin:"
echo "   fantastic-encouragement"
echo ""
echo "3. Service'e tıklayın:"
echo "   web"
echo ""
echo "4. Settings sekmesine gidin"
echo ""
echo "5. Service Name bölümünde:"
echo "   - Mevcut: web"
echo "   - Yeni: cumhuriyet-kutuphanesi yazın"
echo "   - Save butonuna tıklayın"
echo ""
echo "6. Railway otomatik olarak yeni domain oluşturacak:"
echo "   cumhuriyet-kutuphanesi-production-xxxx.up.railway.app"
echo ""
echo "✅ Site içeriği güncellendi:"
echo "   - Navbar: 'Cumhuriyet Kütüphanesi'"
echo "   - Site başlığı: 'Cumhuriyet Anadolu Lisesi Kütüphanesi'"
echo ""
echo "🔗 Mevcut Domain:"
echo "   https://web-production-8d80.up.railway.app"
echo ""

